export const CardData = [
  {
    id: "01F8PJ4NKHEBSA0Y1JY358VB21",
    image: `${process.env.PUBLIC_URL}/assets/images/image_classification.png`,
    title: "Image Classification",
    label: "Image Classification",
  },
  {
    id: "02F8PJ4C71WSCZK9GXFWTYBFRC",
    image: `${process.env.PUBLIC_URL}/assets/images/object_detection.png`,
    title: "Object Detection",
    label: "Object Detection",
  },
  {
    id: "03F8PJ4W3BHYQ8JXGMCQP64WPF",
    image: `${process.env.PUBLIC_URL}/assets/images/human_segmentation.png`,
    title: "Human Segmentation",
    label: "Human Segmentation",
  },
  {
    id: "04F8PJ4W3BHYQ8JXGMCQP64WPF",
    image: `${process.env.PUBLIC_URL}/assets/images/posture_estimation.png`,
    title: "Posture Estimation",
    label: "Posture Estimation",
  },
  {
    id: "05F8PJ4W3BHYQ8JXGMCQP64WPF",
    image: `${process.env.PUBLIC_URL}/assets/images/face_landmark.png`,
    title: "Text toxicity detection",
    label: "Text toxicity detection",
  },
  {
    id: "06F8PJ4W3BHYQ8JXGMCQP64WPF",
    image: `${process.env.PUBLIC_URL}/assets/images/face_landmark.png`,
    title: "Universal Sentence Encoder",
    label: "Universal Sentence Encoder",
  },
  {
    id: "07F8PJ4W3BHYQ8JXGMCQP64WPF",
    image: `${process.env.PUBLIC_URL}/assets/images/face_landmark.png`,
    title: "Voice command recognition",
    label: "Voice command recognition",
  },
  {
    id: "08F8PJ4W3BHYQ8JXGMCQP64WPF",
    image: `${process.env.PUBLIC_URL}/assets/images/face_landmark.png`,
    title: "KNN classifier",
    label: "KNN classifier",
  },
  {
    id: "09F8PJ4W3BHYQ8JXGMCQP64WPF",
    image: `${process.env.PUBLIC_URL}/assets/images/face_landmark.png`,
    title: "Face Detection",
    label: "Face Detection",
  },
  {
    id: "10F8PJ4W3BHYQ8JXGMCQP64WPF",
    image: `${process.env.PUBLIC_URL}/assets/images/face_landmark.png`,
    title: "Semantic segmentation",
    label: "Semantic segmentation",
  },
  {
    id: "11F8PJ4W3BHYQ8JXGMCQP64WPS",
    image: `${process.env.PUBLIC_URL}/assets/images/face_landmark.png`,
    title: "Face Landmark",
    label: "Face Landmark",
  },
  {
    id: "12F8PJ4SRRH2PPWNVNEDFXKK1J",
    image: `${process.env.PUBLIC_URL}/assets/images/hand_pose.png`,
    title: "Hand Pose",
    label: "Hand Pose",
  },
  {
    id: "13F8PJ4W3BHYQ8JXGMCQP64WPF",
    image: `${process.env.PUBLIC_URL}/assets/images/face_landmark.png`,
    title: "Natural language",
    label: "Natural language",
  },
  {
    id: "14F8PJ4W3BHYQ8JXGMCQP64WPF",
    image: `${process.env.PUBLIC_URL}/assets/images/face_landmark.png`,
    title: "Pose Detection",
    label: "Pose Detection",
  },
];
