# prettier-ignore
name: Vercel Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        architecture: [x64]
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
    #- name: Install Dependencies
    #- uses: borales/actions-yarn@v2.3.0
    #  with:
    #    cmd: install
    #- name: Build
    #- uses: borales/actions-yarn@v2.3.0
    #  with:
    #    cmd: build
      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
