# prettier-ignore
name: Vercel Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        architecture: [x64]
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: Use Nodejs ${{ matrix.node-version }} - ${{ matrix.architecture }}
      uses: actions/setup-node@v2
      
    - name: Yarn [Install]
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    #- name: Yarn [Lint]
    #  uses: borales/actions-yarn@v2.0.0
    #  with:
    #    cmd: lint-check
    #- name: Yarn [Test]
    #  uses: borales/actions-yarn@v2.0.0
    #  with:
    #    cmd: test

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        architecture: [x64]
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        yarn build
        
    - name: Vercel Deploy
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
